name: Copy Secrets to TAI

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy secrets to tai repo
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$CSC_KEY_PASSWORD" | gh secret set CSC_KEY_PASSWORD -R darkharasho/tai
          echo "$APPLE_ID" | gh secret set APPLE_ID -R darkharasho/tai
          echo "$APPLE_APP_SPECIFIC_PASSWORD" | gh secret set APPLE_APP_SPECIFIC_PASSWORD -R darkharasho/tai
          echo "$APPLE_TEAM_ID" | gh secret set APPLE_TEAM_ID -R darkharasho/tai
